from utils.llm import llm
import re

def review_agent(state, field):
    """
    The Review Agent evaluates the quality and completeness of outputs generated by other agents.
    It assesses the content based on criteria such as accuracy, clarity, relevance, and comprehensiveness.
    The agent assigns a score from 1-10, provides constructive feedback, and determines whether the output
    meets the required standards (APPROVED) or needs revision (RETRY). This ensures high-quality results
    throughout the research paper analysis workflow.
    """
    content = state.get(field, "")

    response = llm.invoke(f"""
    Evaluate this output:

    {content}

    Give:
    Score (1-10)
    Feedback
    Verdict: APPROVED or RETRY
    """)

    text = response.content

    score_match = re.search(r'(\d+)', text)
    score = int(score_match.group(1)) if score_match else 5

    verdict = "APPROVED" if "APPROVED" in text.upper() else "RETRY"

    return {
        "review_score": score,
        "feedback": text,
        "verdict": verdict
    }